# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
script:
- set -o pipefail && xcodebuild test -project Stanley.xcodeproj -scheme StanleyTests-iOS -destination "platform=iOS Simulator,name=iPhone 7 Plus,OS=10.0" ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild test -project Stanley.xcodeproj -scheme StanleyTests-tvOS -destination "platform=tvOS Simulator,name=Apple TV 1080p,OS=10.0" ONLY_ACTIVE_ARCH=NO | xcpretty
- set -o pipefail && xcodebuild -project Stanley.xcodeproj -scheme StanleyTests-macOS test ONLY_ACTIVE_ARCH=NO | xcpretty
notifications:
    email:
        on_success: never
        on_failure: always
branches:
    only:
        - master
