# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode8.2
language: objective-c
script: ./scripts/travis-ci.sh
after_success:
	- bash <(curl -s https://codecov.io/bash)
notifications:
    email:
        on_success: never
        on_failure: always
branches:
    only:
        - master
 