# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
    batch: true
    branches:
        include: ["master"]
pr:
    autoCancel: true
    branches:
        include: ["master"]

pool:
  vmImage: 'macOS-10.13'

steps:
- task: Xcode@5
  inputs:
    actions: 'test'
    scheme: 'StanleyTests-iOS'
    sdk: 'iphonesimulator'
    destinationPlatformOption: "iOS"
    destinationTypeOption: "simulators"
    destinationSimulators: 'iPhone X'
    xcodeVersion: '10'
    useXcpretty: true
    publishJUnitResults: true
- task: Xcode@5
  inputs:
    actions: 'test'
    scheme: 'StanleyTests-tvOS'
    sdk: 'appletvsimulator'
    destinationPlatformOption: "tvOS"
    destinationTypeOption: "simulators"
    destinationSimulators: 'Apple TV'
    xcodeVersion: '10'
    useXcpretty: true
    publishJUnitResults: true
- task: Xcode@5
  inputs:
    actions: 'test'
    scheme: 'StanleyTests-macOS'
    sdk: 'macosx'
    xcodeVersion: '10'
    useXcpretty: true
    publishJUnitResults: true
- task: ShellScript@2
  inputs:
    scriptPath: "scripts/upload_code_coverage.sh"
